# Day-Two-OpenStack

Materials to support a hands-on lab @ https://bit.ly/2RJaSBL[OpenStack Summit in Berlin].

* The _playbooks_ directory - contains playbooks to setup the instances used in the lab; including day 2 operations meant to be performed against them. 
* The _webapp_ directory - hosts a sample application that is deployed on the instances. 
* The _docs_ directory - contains all the lab exercises that were covered in the _Simplifying Day Two Operations with Ansible_ session. 

Questions? Fee free to email rlopez at redhat.com or dcritch at redhat.com 

# OpenStack Summit 2018: Day Two Operations with Ansible

:numbered!:

=== <<docs/lab0_overview.adoc#overview-of-the-lab,Lab Overview>>
=== <<docs/lab1_ansible_overview.adoc#lab-1-lab-setup, Lab 1 - Ansible Overview>>
=== <<docs/lab2_running_ansible.adoc#lab-2-configuring-and-running-ansible, Lab 2 - Configuring and Running Ansible>>
=== <<docs/lab3_intro_to_playbooks.adoc#lab-3-introduction-to-playbooks, Lab 3 - Introduction to Ansible Playbooks>>
=== <<docs/lab4_intro_vars_facts_incl.adoc#lab4-intro-vars-facts,Lab 4 - Introduction to Variables, Facts, and Includes>>
=== <<docs/lab5_tasks_controls_handlers_tags.adoc#lab-5-task-control-handlers-registered-variables-tags, Lab 5 - Task Control, Handlers, Registered Variables>>
=== <<docs/lab6_comprehensive_review.adoc#lab6-comprehensive-review, Lab 6 - Comprehensive Review>>

# Lab Setup

This lab can be recreated in your own environment to complete at your own pace.

If you do not have an existing OpenStack cluster, you can run the following on a bare-metal host to deploy devstack and then the lab environment on top:

`$ ansible-playbook playbooks/deploy_devstack.yml`

To deploy the lab against an existing OpenStack cloud, create an ansible variables file (see `playbooks/devstack_env.yml` for an example) and run the following:

`$ ansible-playbook playbooks/deploy_webapp.yml -e @playbooks/devstack_env.yml`

`$ ansible-playbook webapp/deploy.yml`

`$ ansible-playbook playbooks/make_loadbalancer.yml -e @playbooks/devstack_env.yml`

NOTE: If using an existing environment, it must support the `cinder-backup` and `octavia` services.
