---
- name: install and configure devstack
  hosts: devstack
  vars:
    openstack_repos:
    - https://git.openstack.org/openstack-dev/devstack
    - git://git.openstack.org/openstack/cinder.git
    - git://git.openstack.org/openstack/glance.git
    - git://git.openstack.org/openstack/keystone.git
    - git://git.openstack.org/openstack/neutron.git
    - https://git.openstack.org/openstack/neutron-lbaas
    - git://git.openstack.org/openstack/nova.git
    - https://git.openstack.org/openstack/octavia
    - git://git.openstack.org/openstack/requirements.git
    - git://git.openstack.org/openstack/swift.git
  handlers:
  - name: restart sshd
    systemd:
      name: sshd
      state: restarted
    become: true
  tasks:
#  - name: stop firewalld
#    systemd:
#      name: firewalld
#      state: stopped
#      enabled: false
#    become: true
  - name: create stack user
    user:
      name: stack
      shell: /bin/bash
      password: $6$rounds=656000$47cizb4beOY.uB9c$wTlFCrP62g/M0.UNl0IHLOOw.fuWvJwCQLLS8UeruI1T/tbAdKd8Wzhsy7SandrOtROwBn7FBZHTaZcZciXMd/
      generate_ssh_key: yes
      ssh_key_bits: 2048
      ssh_key_file: .ssh/id_rsa
      home: /opt/stack
    become: true
  - name: give sudo access to stack user
    copy:
      dest: /etc/sudoers.d/stack
      content: 'stack ALL=(ALL) NOPASSWD: ALL'
      mode: 0440
    become: true
  - name: allow ssh access with passwords
    lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^PasswordAuthentication no'
      line: 'PasswordAuthentication yes'
    become: true
    notify:
    - restart sshd
  - name: install epel
    package:
      name: epel-release
      state: installed
    become: true
  - name: install packages
    package:
      name: ['git', 'ansible', 'python-pip', 'policycoreutils-python', 'screen']
      state: installed
    become: true
  - name: clone lab repo
    git:
      repo: https://github.com/RHsyseng/day-two-openstack.git
      dest: /opt/stack/day-two-openstack
    become: true
    become_user: stack
  - name: clone openstack repos
    git:
      repo: '{{ item }}'
      dest: '/opt/stack/{{ item.split("/")[-1].split(".")[0] }}'
      force: yes
      version: 'stable/rocky'
    with_items: '{{ openstack_repos }}'
    become: true
    become_user: stack
  - name: update pip
    command: pip install --upgrade pip
    become: true
  - name: update setuptools
    command: pip install --upgrade setuptools
    become: true
  - name: copy webdb image
    copy:
      src: '/srv/images/centos-7-x86_64-webdb.qcow2'
      dest: '/opt/stack/centos-7-x86_64-webdb.qcow2'
    become: true
    become_user: stack
  - name: copy octavia image
    copy:
      src: '/srv/images/amphora-x64-haproxy.qcow2'
      dest: '/opt/stack/octavia/diskimage-create/amphora-x64-haproxy.qcow2'
    become: true
    become_user: stack
  - name: get lax on keys
    copy:
      dest: /opt/stack/.ssh/config
      content: |
        StrictHostKeyChecking=no
        UserKnownHostsFile=/dev/null
      mode: '0600'
    become: true
    become_user: stack
  - name: add devstack sourcing to bashrc
    lineinfile:
      path: /opt/stack/.bashrc
      line: 'source /opt/stack/devstack/openrc demo'
    become: true
    become_user: stack
  - name: copy localrc config file
    copy:
      dest: /opt/stack/devstack/local.conf
      content: |
        [[local|localrc]]
        # Load the external LBaaS plugin.
        enable_plugin neutron-lbaas https://git.openstack.org/openstack/neutron-lbaas
        enable_plugin octavia https://git.openstack.org/openstack/octavia
        DATABASE_PASSWORD=password
        ADMIN_PASSWORD=password
        SERVICE_PASSWORD=password
        RABBIT_PASSWORD=password
        # Enable Logging
        LOGFILE=$DEST/logs/stack.sh.log
        VERBOSE=True
        LOG_COLOR=True
        # Pre-requisite
        ENABLED_SERVICES=rabbit,mysql,key
        # Nova
        ENABLED_SERVICES+=,n-api,n-cpu,n-cond,n-sch,n-api-meta
        # Glance
        ENABLED_SERVICES+=,g-api,g-reg
        # Neutron
        ENABLE_ISOLATED_METADATA=True
        ENABLED_SERVICES+=,q-svc,q-agt,q-dhcp,q-l3,q-meta
        # Enable LBaaS v2
        OCTAVIA_AMP_BASE_OS=centos
        OCTAVIA_AMP_IMAGE_SIZE=10
        #DISABLE_AMP_IMAGE_BUILD=True
        ENABLED_SERVICES+=,q-lbaasv2
        ENABLED_SERVICES+=,octavia,o-cw,o-hk,o-hm,o-api
        # Swift
        SWIFT_HASH=66a3d6b56c1f479c8b4e70ab5c2000f5
        SWIFT_REPLICAS=1
        SWIFT_DATA_DIR=$DEST/data
        ENABLED_SERVICES+=,s-proxy,s-object,s-container,s-account
        # Cinder
        ENABLED_SERVICES+=,c-api,c-vol,c-sch,c-bak
        enable_service placement-api
    become: true
    become_user: stack
  - name: create lab deploy script
    copy:
      dest: /opt/stack/deploy_lab.sh
      content: |
        #/bin/bash
        source /opt/stack/devstack/openrc demo
        cd ~/day-two-openstack
        ansible-playbook playbooks/deploy_webapp.yml -e @playbooks/devstack_env.yml && \
        ansible-playbook webapp/deploy.yml && \
        ansible-playbook playbooks/make_loadbalancer.yml -e @playbooks/devstack_env.yml
          if [[ x$1 == x"test" ]]; then
            ansible-playbook playbooks/cinder_backup_final.yml && \
            ansible-playbook playbooks/cinder_restore_using_include.yml && \
            ansible-playbook playbooks/rolling_upgrade.yml
            ## reset
            ansible-playbook playbooks/delete_webapp.yml && \
            ansible-playbook playbooks/delete_loadbalancer.yml -e @playbooks/devstack_env.yml && \
            ansible-playbook playbooks/deploy_webapp.yml -e @playbooks/devstack_env.yml && \
            ansible-playbook webapp/deploy.yml && \
            ansible-playbook playbooks/make_loadbalancer.yml -e @playbooks/devstack_env.yml
          fi
      mode: 0755
    become: true
    become_user: stack
  - name: create first boot script
    copy:
      dest: /first-boot.sh
      content: |
        #!/bin/bash
        set -e
        export TERM=xterm
        cd /opt/stack/devstack
        su - stack -c /opt/stack/devstack/stack.sh
        sed -i 's/default_store = swift/default_store = file/g' /etc/glance/glance-api.conf
        systemctl restart devstack@g-api.service
        iptables -F
        su - stack -c /opt/stack/deploy_lab.sh
      mode: 0755
    become: true
  - name: deploy devstack
    shell: /opt/stack/devstack/stack.sh
    args:
      chdir: /opt/stack/devstack
      creates: /opt/stack/devstack/.stackenv
    become: true
    become_user: stack
    tags:
    - deploy
  - name: shutdown iptables because I dont know why
    shell: iptables -F
    become: true
    tags:
    - deploy
  - name: chunk big files in glance
    lineinfile:
      path: '/etc/glance/glance-api.conf'
      line: 'swift_store_large_object_size = 500'
      insertafter: 'swift_store_config_file = /etc/glance/glance-swift-store.conf'
    become: true
    tags:
    - deploy
  - name: set file to be default glance store
    lineinfile:
      path: '/etc/glance/glance-api.conf'
      regexp: 'default_store = swift'
      line: 'default_store = file'
    become: true
    tags:
    - deploy
  - name: restart glance-api
    systemd:
      name: 'devstack@g-api.service'
      state: restarted
    become: true
    tags:
    - deploy
  - name: run lab deploy script
    shell: /opt/stack/deploy_lab.sh
    become: true
    become_user: stack
    tags:
    - deploy
    - lab_deploy
